# Generated by Django 5.0.2 on 2024-03-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RazonSocial', models.CharField(max_length=30)),
                ('Salas', models.IntegerField()),
                ('idDistrito', models.IntegerField()),
                ('Direccion', models.CharField(max_length=100)),
                ('Telefonos', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=80)),
                ('fecha_estreno', models.CharField(max_length=10)),
                ('director', models.CharField(max_length=50)),
                ('generos', models.CharField(max_length=10)),
                ('id_clasificacion', models.IntegerField()),
                ('id_estado', models.IntegerField()),
                ('duracion', models.CharField(max_length=3)),
                ('link', models.CharField(max_length=20)),
                ('reparto', models.TextField()),
                ('sinopsis', models.TextField()),
            ],
        ),
    ]
