# Generated by Django 5.0.2 on 2024-03-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cine',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
